using RidePal.Data.Context;
using RidePal.Data.Models;
using RidePal.Data.Models.DeezerAPIModels;
using RidePal.Service.Contracts;
using RidePal.Service.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace RidePal.Service
{
    public class DatabaseSeedService : IDatabaseSeedService
    {
        private readonly RidePalDbContext context;
        HttpClient client = new HttpClient();
        Dictionary<long, Artist> Artists = new Dictionary<long, Artist>();
        Dictionary<long, Album> Albums = new Dictionary<long, Album>();
        Dictionary<long, Track> Tracks = new Dictionary<long, Track>();
        Dictionary<long, Genre> Genres = new Dictionary<long, Genre>();
        private readonly IGeneratePlaylistService service;

        public DatabaseSeedService(RidePalDbContext _context, IGeneratePlaylistService _service)
        {
            this.context = _context;
            this.service = _service;
        }

        /// <summary>
        /// Downloads tracks from the external Deezer API according to a specified music genre 
        /// and deserializes the downloaded data to local objects: tracks, artists, albums and music genres.
        /// </summary>
        /// <param name="incomingGenre">The music genre of the tracks to download</param>
        /// <returns>Void</returns>
        public async Task DownloadTrackData(string incomingGenre)
        {
            string startUrl = $"http://api.deezer.com/search/playlist?q={incomingGenre}";

            var response = await client.GetAsync(startUrl);

            var jsonString = await response.Content.ReadAsStringAsync();

            var deezerPlaylistCollection = JsonSerializer.Deserialize<DeezerPlaylistCollection>(jsonString);

            foreach (var item in deezerPlaylistCollection.DeezerPlaylists)
            {
                await TraverseTracklist(item.TracklistUrl, incomingGenre);
            }

            await context.SaveChangesAsync();
        }

        /// <summary>
        /// Supporting method, which traverses the provided tracklist by Deezer API 
        /// and adds its tracks, artists, albums and genres to the local database
        /// </summary>
        /// <param name="currentTracklistUrl">URL of the tracklist at Deezer API</param>
        /// <param name="incomingGenre">String of the music genre</param>
        /// <returns>Void</returns>
        public async Task TraverseTracklist(string currentTracklistUrl, string incomingGenre)
        {
            Genre genre = new Genre();
            genre.Name = incomingGenre;
            genre.Id = context.Genres.Count() + 1;

            int trackCountBeforeSeed = context.Tracks.Count();

            while (currentTracklistUrl != null)
            {
                if (Tracks.Count >= trackCountBeforeSeed + 250) //250 tracks with each genre
                {
                    break;
                }

                var response = await client.GetAsync(currentTracklistUrl);

                var jsonString = await response.Content.ReadAsStringAsync();

                var deezerTrackCollection = JsonSerializer.Deserialize<DeezerTrackCollection>(jsonString);

                foreach (var track in deezerTrackCollection.Tracks)
                {
                    if (Tracks.ContainsKey(track.Id))
                    {
                        continue;
                    }
                    else
                    {
                        Tracks.Add(track.Id, track);
                    }

                    if (Albums.ContainsKey(track.Album.Id))
                    {
                        track.Album = Albums[track.Album.Id];
                    }
                    else
                    {
                        Albums.Add(track.Album.Id, track.Album);
                    }

                    if (Artists.ContainsKey(track.Artist.Id))
                    {
                        track.Artist = Artists[track.Artist.Id];
                    }
                    else
                    {
                        Artists.Add(track.Artist.Id, track.Artist);
                    }

                    track.Genre = genre;

                    if (Genres.ContainsKey(track.Genre.Id))
                    {
                        track.Genre = Genres[track.Genre.Id];
                    }
                    else
                    {
                        Genres.Add(track.Genre.Id, track.Genre);
                    }

                    context.Tracks.Add(track);
                }

                currentTracklistUrl = deezerTrackCollection.NextPageUrl;
            }
        }

        /// <summary>
        /// Supporting method to seed the local database with playlists generated by the app's algorithm
        /// </summary>
        /// <returns>Void</returns>
        public IEnumerable<GeneratePlaylistDTO> GeneratePlaylists()
        {
            return new GeneratePlaylistDTO[]
            {
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Ihtiman",
                    PlaylistName = "Metal and mix",
                    RepeatArtist = true,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 20
                        },
                        {
                            "metal", 40
                        },
                        {
                            "pop", 20
                        },
                        {
                            "jazz", 20
                        }

                    },
                    UserId = 1
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Varna",
                    PlaylistName = "To the sea",
                    RepeatArtist = false,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 0
                        },
                        {
                            "metal", 60
                        },
                        {
                            "pop", 40
                        },
                        {
                            "jazz", 0
                        }

                    },
                    UserId = 2
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Plovdiv",
                    PlaylistName = "Home",
                    RepeatArtist = true,
                    UseTopTracks = false,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 100
                        },
                        {
                            "metal", 0
                        },
                        {
                            "pop", 0
                        },
                        {
                            "jazz", 0
                        }

                    },
                    UserId = 1
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Harmanli",
                    PlaylistName = "Harmanli trip",
                    RepeatArtist = false,
                    UseTopTracks = false,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 10
                        },
                        {
                            "metal", 20
                        },
                        {
                            "pop", 50
                        },
                        {
                            "jazz", 20
                        }

                    },
                    UserId = 2
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Targovishte",
                    Destination = "Plovdiv",
                    PlaylistName = "To Targovishte",
                    RepeatArtist = false,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 0
                        },
                        {
                            "metal", 0
                        },
                        {
                            "pop", 0
                        },
                        {
                            "jazz", 100
                        }

                    },
                    UserId = 2
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Kardzhali",
                    Destination = "Plovdiv",
                    PlaylistName = "Plovdiv Kardzhali",
                    RepeatArtist = true,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 20
                        },
                        {
                            "metal", 80
                        },
                        {
                            "pop", 0
                        },
                        {
                            "jazz", 0
                        }

                    },
                    UserId = 1
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Svoge",
                    PlaylistName = "Fest mix",
                    RepeatArtist = false,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 40
                        },
                        {
                            "metal", 20
                        },
                        {
                            "pop", 10
                        },
                        {
                            "jazz", 30
                        }

                    },
                    UserId = 2
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Lukovit",
                    PlaylistName = "Metal & Rock",
                    RepeatArtist = true,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 50
                        },
                        {
                            "metal", 50
                        },
                        {
                            "pop", 0
                        },
                        {
                            "jazz", 0
                        }

                    },
                    UserId = 1
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Svilengrad",
                    PlaylistName = "Pop Svilengrad",
                    RepeatArtist = false,
                    UseTopTracks = false,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 0
                        },
                        {
                            "metal", 0
                        },
                        {
                            "pop", 100
                        },
                        {
                            "jazz", 0
                        }

                    },
                    UserId = 1
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Samokov",
                    PlaylistName = "Small trip pop and jazz",
                    RepeatArtist = true,
                    UseTopTracks = false,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 0
                        },
                        {
                            "metal", 0
                        },
                        {
                            "pop", 50
                        },
                        {
                            "jazz", 50
                        }

                    },
                    UserId = 2
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Burgas",
                    Destination = "Varna",
                    PlaylistName = "Seaside trip",
                    RepeatArtist = false,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 20
                        },
                        {
                            "metal", 20
                        },
                        {
                            "pop", 0
                        },
                        {
                            "jazz", 60
                        }

                    },
                    UserId = 1
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Varna",
                    Destination = "Burgas",
                    PlaylistName = "Varna Burgas trip",
                    RepeatArtist = true,
                    UseTopTracks = false,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 50
                        },
                        {
                            "metal", 10
                        },
                        {
                            "pop", 30
                        },
                        {
                            "jazz", 10
                        }

                    },
                    UserId = 2
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Malko Tarnovo",
                    PlaylistName = "Jazz time",
                    RepeatArtist = true,
                    UseTopTracks = false,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 0
                        },
                        {
                            "metal", 0
                        },
                        {
                            "pop", 0
                        },
                        {
                            "jazz", 100
                        }

                    },
                    UserId = 1
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Plovdiv",
                    Destination = "Svilengrad",
                    PlaylistName = "Border",
                    RepeatArtist = true,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 50
                        },
                        {
                            "metal", 0
                        },
                        {
                            "pop", 50
                        },
                        {
                            "jazz", 0
                        }

                    },
                    UserId = 1
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Ruse",
                    Destination = "Samokov",
                    PlaylistName = "Danube",
                    RepeatArtist = true,
                    UseTopTracks = false,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 0
                        },
                        {
                            "metal", 50
                        },
                        {
                            "pop", 50
                        },
                        {
                            "jazz", 0
                        }

                    },
                    UserId = 2
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Burgas",
                    Destination = "Varna",
                    PlaylistName = "Birthday seaside trip",
                    RepeatArtist = false,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 20
                        },
                        {
                            "metal", 20
                        },
                        {
                            "pop", 20
                        },
                        {
                            "jazz", 40
                        }

                    },
                    UserId = 1
                },
                new GeneratePlaylistDTO()
                {
                    StartLocation = "Sofia",
                    Destination = "Elin Pelin",
                    PlaylistName = "Work",
                    RepeatArtist = false,
                    UseTopTracks = true,
                    GenrePercentage = new Dictionary<string, int>()
                    {
                        {
                            "rock", 50
                        },
                        {
                            "metal", 10
                        },
                        {
                            "pop", 30
                        },
                        {
                            "jazz", 10
                        }

                    },
                    UserId = 2
                }
            };
        }
    }
}
